#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# $1 = 0 -> 既存のブランチへの切り替え
# $1 = 1 -> 新しいブランチを作成した場合

# 新しいブランチを作成した場合
if [ "$1" -eq 1 ]; then
  echo "新しいブランチが作成されました: $2"
  
  # 空コミットを実行
  git commit --allow-empty -m "Initial empty commit" --no-verify
else
  echo "既存のブランチに切り替えました: $2"
fi