#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
# .husky/post-checkout

# 現在のブランチ名を取得
current_branch=$(git symbolic-ref --short HEAD)

# 新しく作成されたブランチを判定
if [ "$1" = "1" ] && [ "$current_branch" != "$2" ]; then
  echo "新しいブランチが作成されました: $2"
  # 空コミットを実行
  git commit --allow-empty -m "Initial empty commit" --no-verify
else
  echo "既存のブランチに切り替えました: $2"
fi